//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 01:40:54 PM CET 
//


package com.swimmingsprite.xmlservice.entity.invoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Delivery" type="{http://www.example.com/Invoice}Date"/&gt;
 *         &lt;element name="Invoice" type="{http://www.example.com/Invoice}Date"/&gt;
 *         &lt;element name="Due" type="{http://www.example.com/Invoice}Date"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dates", propOrder = {

})
public class Dates {

    @XmlElement(name = "Delivery", required = true)
    protected Date delivery;
    @XmlElement(name = "Invoice", required = true)
    protected Date invoice;
    @XmlElement(name = "Due", required = true)
    protected Date due;

    /**
     * Gets the value of the delivery property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDelivery() {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDelivery(Date value) {
        this.delivery = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setInvoice(Date value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the due property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDue() {
        return due;
    }

    /**
     * Sets the value of the due property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDue(Date value) {
        this.due = value;
    }

}
