//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 01:40:54 PM CET 
//


package com.swimmingsprite.xmlservice.entity.invoice;

import java.math.BigInteger;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GeneralType" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="MonthAndYear" type="{http://www.example.com/Invoice}MonthAndYearType"/&gt;
 *         &lt;element name="IsTaxPayer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="GeneratedBy" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="Dates" type="{http://www.example.com/Invoice}Dates"/&gt;
 *         &lt;element name="Bank" type="{http://www.example.com/Invoice}Bank"/&gt;
 *         &lt;element name="Supplier" type="{http://www.example.com/Invoice}SupplierOrCustomerType"/&gt;
 *         &lt;element name="Customer" type="{http://www.example.com/Invoice}SupplierOrCustomerType"/&gt;
 *         &lt;element name="Price" type="{http://www.example.com/Invoice}Price"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="Document")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentType", propOrder = {
    "generalType",
    "type",
    "number",
    "monthAndYear",
    "isTaxPayer",
    "generatedBy",
    "dates",
    "bank",
    "supplier",
    "customer",
    "price"
})
public class DocumentType {

    @XmlElement(name = "GeneralType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String generalType;
    @XmlElement(name = "Type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String type;
    @XmlElement(name = "Number", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger number;
    @XmlElement(name = "MonthAndYear", required = true)
    protected String monthAndYear;
    @XmlElement(name = "IsTaxPayer")
    protected boolean isTaxPayer;
    @XmlElement(name = "GeneratedBy", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String generatedBy;
    @XmlElement(name = "Dates", required = true)
    protected Dates dates;
    @XmlElement(name = "Bank", required = true)
    protected Bank bank;
    @XmlElement(name = "Supplier", required = true)
    protected SupplierOrCustomerType supplier;
    @XmlElement(name = "Customer", required = true)
    protected SupplierOrCustomerType customer;
    @XmlElement(name = "Price", required = true)
    protected Price price;

    /**
     * Gets the value of the generalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralType() {
        return generalType;
    }

    /**
     * Sets the value of the generalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralType(String value) {
        this.generalType = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the monthAndYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthAndYear() {
        return monthAndYear;
    }

    /**
     * Sets the value of the monthAndYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthAndYear(String value) {
        this.monthAndYear = value;
    }

    /**
     * Gets the value of the isTaxPayer property.
     * 
     */
    public boolean isIsTaxPayer() {
        return isTaxPayer;
    }

    /**
     * Sets the value of the isTaxPayer property.
     * 
     */
    public void setIsTaxPayer(boolean value) {
        this.isTaxPayer = value;
    }

    /**
     * Gets the value of the generatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratedBy() {
        return generatedBy;
    }

    /**
     * Sets the value of the generatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratedBy(String value) {
        this.generatedBy = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link Dates }
     *     
     */
    public Dates getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dates }
     *     
     */
    public void setDates(Dates value) {
        this.dates = value;
    }

    /**
     * Gets the value of the bank property.
     * 
     * @return
     *     possible object is
     *     {@link Bank }
     *     
     */
    public Bank getBank() {
        return bank;
    }

    /**
     * Sets the value of the bank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bank }
     *     
     */
    public void setBank(Bank value) {
        this.bank = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierOrCustomerType }
     *     
     */
    public SupplierOrCustomerType getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierOrCustomerType }
     *     
     */
    public void setSupplier(SupplierOrCustomerType value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierOrCustomerType }
     *     
     */
    public SupplierOrCustomerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierOrCustomerType }
     *     
     */
    public void setCustomer(SupplierOrCustomerType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setPrice(Price value) {
        this.price = value;
    }

}
